// src/services/export/pdfExport.js
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { format } from 'date-fns';
import { registerArabicPdfFont, ARABIC_PDF_FONT } from '../../utils/arabicFont';
import {
  containsArabicInValues,
  getTextAlignment,
  prepareExportText,
} from '../../utils/exportText';

const applyPdfFontStyle = (doc, useArabicFont, style = 'normal') => {
  if (useArabicFont) {
    doc.setFont(ARABIC_PDF_FONT, style === 'bold' ? 'bold' : 'normal');
    return;
  }

  doc.setFont('helvetica', style);
};

/**
 * Exporte des données au format PDF avec un design professionnel
 */
export const exportPDF = async ({
  title = 'Rapport',
  subtitle = '',
  columns = [],
  data = [],
  filename = 'rapport.pdf',
  logo = null,
  userName = 'Utilisateur',
  companyName = "L'arte ERP",
  summary = null,
  orientation = 'auto',
  rowFormatter = null,
  dateFormat = 'dd/MM/yyyy HH:mm',
  primaryColor = '#B8863B'
}) => {
  try {
    if (!data || data.length === 0) {
      throw new Error('Aucune donnée à exporter');
    }

    let finalOrientation = orientation;
    if (orientation === 'auto') {
      finalOrientation = columns.length > 7 ? 'landscape' : 'portrait';
    }

    let exportData = data;
    if (rowFormatter && typeof rowFormatter === 'function') {
      exportData = data.map(rowFormatter);
    }

    const previewValues = [
      title,
      subtitle,
      userName,
      companyName,
      ...columns.map((col) => col.label),
      ...exportData.flatMap((row) => columns.map((col) => row[col.accessor])),
    ];
    const useArabicFont = containsArabicInValues(previewValues);

    const doc = new jsPDF({
      orientation: finalOrientation,
      unit: 'mm',
      format: 'a4'
    });

    if (useArabicFont) {
      await registerArabicPdfFont(doc);
    }

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 16;
    const currentDate = format(new Date(), dateFormat);

    let yPosition = 15;

    doc.setFillColor('#B8863B');
    doc.rect(0, 0, pageWidth, 6, 'F');

    yPosition = 20;

    doc.setFontSize(20);
    applyPdfFontStyle(doc, useArabicFont, 'bold');
    doc.setTextColor('#B8863B');
    doc.text(prepareExportText(companyName), pageWidth / 2, yPosition, {
      align: getTextAlignment(companyName, 'center'),
    });

    doc.setFontSize(14);
    applyPdfFontStyle(doc, useArabicFont, 'bold');
    doc.setTextColor('#2B2B2B');
    doc.text(prepareExportText(title), pageWidth / 2, yPosition + 9, {
      align: getTextAlignment(title, 'center'),
    });

    if (subtitle) {
      doc.setFontSize(10);
      applyPdfFontStyle(doc, useArabicFont, 'normal');
      doc.setTextColor('#666666');
      doc.text(prepareExportText(subtitle), pageWidth / 2, yPosition + 16, {
        align: getTextAlignment(subtitle, 'center'),
      });
      yPosition = yPosition + 26;
    } else {
      yPosition = yPosition + 20;
    }

    doc.setFontSize(8);
    applyPdfFontStyle(doc, useArabicFont, 'normal');
    doc.setTextColor('#666666');

    const metaData = [
      `Generated by: ${userName || 'User'}`,
      `Date: ${currentDate}`,
      `Total: ${exportData.length} rows`
    ];

    let xPos = margin;
    metaData.forEach((text) => {
      doc.text(prepareExportText(text), xPos, yPosition, {
        align: getTextAlignment(text, 'left'),
      });
      xPos += doc.getTextWidth(prepareExportText(text)) + 12;
    });

    const metaRight = [
      'Version: 2.0',
      `Reference: ${format(new Date(), 'yyyyMMddHHmmss')}`
    ];

    let rightX = pageWidth - margin;
    metaRight.forEach((text, index) => {
      const prepared = prepareExportText(text);
      const textWidth = doc.getTextWidth(prepared);
      doc.text(prepared, rightX - textWidth, yPosition + (index * 4), {
        align: getTextAlignment(text, 'right'),
      });
    });

    yPosition += 10;

    doc.setDrawColor('#E8E0D8');
    doc.setLineWidth(0.3);
    doc.line(margin, yPosition, pageWidth - margin, yPosition);
    yPosition += 6;

    if (summary && typeof summary === 'object' && Object.keys(summary).length > 0) {
      let summaryItems = [];

      if (Array.isArray(summary)) {
        summaryItems = summary;
      } else {
        summaryItems = Object.keys(summary).map(key => ({
          label: key,
          value: summary[key]
        }));
      }

      if (summaryItems.length > 0) {
        const colsPerRow = Math.min(4, summaryItems.length);
        const cardWidth = (pageWidth - margin * 2 - (colsPerRow - 1) * 6) / colsPerRow;
        const cardHeight = 20;

        let sumX = margin;
        let sumY = yPosition;

        summaryItems.forEach((item, index) => {
          if (index > 0 && index % colsPerRow === 0) {
            sumX = margin;
            sumY += cardHeight + 5;
          }

          doc.setFillColor('#F8F7F4');
          doc.setDrawColor('#E8E0D8');
          doc.roundedRect(sumX, sumY, cardWidth, cardHeight, 3, 3, 'FD');

          doc.setFontSize(7);
          applyPdfFontStyle(doc, useArabicFont, 'normal');
          doc.setTextColor('#888888');
          doc.text(prepareExportText(String(item.label)), sumX + 5, sumY + 6, {
            align: getTextAlignment(item.label, 'left'),
          });

          doc.setFontSize(12);
          applyPdfFontStyle(doc, useArabicFont, 'bold');
          doc.setTextColor('#2B2B2B');
          const value = item.value;
          const formattedValue = typeof value === 'number' ? value.toLocaleString() : String(value);
          doc.text(prepareExportText(formattedValue), sumX + 5, sumY + 16, {
            align: getTextAlignment(formattedValue, 'left'),
          });

          sumX += cardWidth + 6;
        });

        yPosition = sumY + cardHeight + 10;
      }
    }

    if (!columns || columns.length === 0) {
      throw new Error('Aucune colonne définie pour le tableau');
    }

    const cleanColumns = columns.map(col => ({
      header: prepareExportText(col.label || col.accessor || 'Column'),
      dataKey: col.accessor,
      align: col.align || getTextAlignment(col.label, 'left')
    }));

    const cleanData = exportData.map(row => {
      const obj = {};
      columns.forEach(col => {
        let value = row[col.accessor];
        if (value === undefined || value === null) {
          value = '';
        }
        if (col.formatter && typeof col.formatter === 'function') {
          value = col.formatter(value, row);
        }
        obj[col.accessor] = prepareExportText(String(value));
      });
      return obj;
    });

    const styles = {
      font: useArabicFont ? ARABIC_PDF_FONT : 'helvetica',
      fontSize: 8,
      cellPadding: { top: 3, bottom: 3, left: 2, right: 2 },
      lineColor: '#E8E0D8',
      lineWidth: 0.1,
      textColor: '#2B2B2B',
      overflow: 'linebreak',
      valign: 'middle'
    };

    const headStyles = {
      fillColor: '#B8863B',
      textColor: '#FFFFFF',
      font: useArabicFont ? ARABIC_PDF_FONT : 'helvetica',
      fontSize: 8,
      fontStyle: 'bold',
      halign: useArabicFont ? 'right' : 'center',
      valign: 'middle',
      cellPadding: { top: 3, bottom: 3, left: 2, right: 2 }
    };

    const alternateRowStyles = {
      fillColor: '#F8F7F4'
    };

    const columnStyles = {};
    const totalCols = cleanColumns.length;
    const baseWidth = Math.min(40, (pageWidth - margin * 2 - 10) / totalCols);

    cleanColumns.forEach((col, index) => {
      let maxLen = col.header.length;
      cleanData.slice(0, 50).forEach(row => {
        const val = row[col.dataKey];
        if (val && String(val).length > maxLen) {
          maxLen = String(val).length;
        }
      });
      let width = Math.max(12, Math.min(45, Math.max(baseWidth, maxLen * 1.5)));
      columnStyles[index] = {
        halign: col.align || getTextAlignment(col.header, 'left'),
        cellWidth: width
      };
    });

    autoTable(doc, {
      columns: cleanColumns,
      body: cleanData,
      startY: yPosition,
      margin: { left: margin, right: margin, top: 2, bottom: 10 },
      styles,
      headStyles,
      alternateRowStyles,
      columnStyles,
      tableWidth: 'auto',
      didDrawPage: function(data) {
        const pageNumber = data.pageNumber;
        const totalPages = doc.internal.getNumberOfPages();

        doc.setFontSize(7);
        applyPdfFontStyle(doc, useArabicFont, 'normal');
        doc.setTextColor('#999999');

        doc.setDrawColor('#E8E0D8');
        doc.setLineWidth(0.2);
        doc.line(margin, pageHeight - 14, pageWidth - margin, pageHeight - 14);

        const footerLeft = prepareExportText(`${companyName} - ${new Date().getFullYear()}`);
        doc.text(footerLeft, margin, pageHeight - 7, {
          align: getTextAlignment(footerLeft, 'left'),
        });

        const footerCenter = `Page ${pageNumber} / ${totalPages}`;
        doc.text(footerCenter, pageWidth / 2, pageHeight - 7, { align: 'center' });

        const footerRight = prepareExportText(`Printed on ${format(new Date(), 'dd/MM/yyyy HH:mm')}`);
        doc.text(footerRight, pageWidth - margin, pageHeight - 7, {
          align: getTextAlignment(footerRight, 'right'),
        });
      },
      didParseCell: function(data) {
        if (data.cell && data.cell.raw && typeof data.cell.raw === 'string' && data.cell.raw.length > 60) {
          data.cell.raw = data.cell.raw.substring(0, 57) + '...';
        }
        if (data.section === 'body' && data.column && typeof data.cell.raw === 'number') {
          data.cell.raw = data.cell.raw.toLocaleString();
        }
        if (useArabicFont && data.cell && typeof data.cell.raw === 'string') {
          data.cell.styles.halign = getTextAlignment(data.cell.raw, data.cell.styles.halign || 'left');
        }
      }
    });

    await new Promise((resolve) => setTimeout(resolve, 150));
    doc.save(filename);

    return { success: true, filename, rowCount: exportData.length };
  } catch (error) {
    console.error('Erreur lors de l\'export PDF:', error);
    throw error;
  }
};

/**
 * Exporte un tableau simple au format PDF
 */
export const exportTableToPDF = async ({
  title,
  headers,
  rows,
  filename = 'tableau.pdf',
  userName = 'Utilisateur',
  summary = null
}) => {
  if (!headers || headers.length === 0) {
    throw new Error('Aucun en-tête défini');
  }

  const columns = headers.map(header => ({
    label: header,
    accessor: header.toLowerCase().replace(/ /g, '_'),
    align: 'left'
  }));

  const data = rows.map(row => {
    const obj = {};
    headers.forEach((header, index) => {
      const key = header.toLowerCase().replace(/ /g, '_');
      obj[key] = row[index] !== undefined ? String(row[index]) : '';
    });
    return obj;
  });

  return exportPDF({
    title,
    columns,
    data,
    filename,
    userName,
    summary
  });
};

/**
 * Export simple de données
 */
export const exportDataToPDF = (data, columns, title, filename) => {
  return exportPDF({
    title: title || 'Export PDF',
    columns: columns || [],
    data: data || [],
    filename: filename || 'export.pdf'
  });
};

export default exportPDF;